str(cars)
plot(cars[, "speed"], cars[, "dist"], xlab = "Speed", ylab = "Distance")
slrModel <- lm(dist ~ speed, data = cars)
str(slrModel)
summary(slrModel)
coef(slrModel)
plot(cars[, "speed"], cars[, "dist"], xlab = "Speed", ylab = "Distance")
abline(slrModel, col = "Blue")
abline(slrModel, col = "Blue")
dev.off()
graphics.off()
library(lattice)
attach(mtcars)
search()
"mtcars" %in% search()
head(mtcars$mpg)
head(mtcars[, "mpg"])
head(mpg)
gear.f <- factor(gear, levels = c(3, 4, 5), labels = c("3gears", "4gears", "5gears"))
cyl.f <- factor(cyl, levels = c(4, 6, 8), labels = c("4cyl", "6cyl", "8cyl"))
densityplot(~mpg, main = "Density Plot", xlab = "Miles per Gallon")
densityplot(~mpg | cyl.f, main = "Density Plot by Number of Cylinders", xlab = "Miles per Gallon")
xyplot(mpg ~ wt | cyl.f * gear.f, main = "Scatterplots by Cylinders and Gears", 
    ylab = "Miles per Gallon", xlab = "Car Weight")
splom(mtcars[, c(1, 3:6)], main = "MTCARS Data")
detach(mtcars)
"mtcars" %in% search()
graphics.off()
